name: Sync with Crowdin

on:
  schedule:
    - cron: '0 16 * * SUN'
  workflow_dispatch:

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Quote sources
      run: ./.github/scripts/quote-sources.sh
      shell: bash

    - name: Sync with Crowdin
      uses: crowdin/github-action@1.4.8
      with:
        upload_sources: true
        upload_translations: true
        download_translations: true
        config: '.crowdin.yml'
        commit_message: 'Update Crowdin translations'
        # FIXME: Commit directly to master
        pull_request_title: 'Update Crowdin translations'
        export_only_approved: false
        skip_untranslated_files: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

    # FIXME: The commit action is failing with insufficient permissions
    # - name: Unquote translations
    #   run: ./.github/scripts/unquote-translations.sh
    #   shell: bash

    # - name: Commit
    #   uses: EndBug/add-and-commit@v9
    #   with:
    #     commit: '--amend'
    #     default_author: 'github_actions'
